DELETE FROM DEPARTMENT;
--DELETE FROM EMPLOYEE;
--COMMIT;

INSERT INTO DEPARTMENT VALUES (101, 'Java');
INSERT INTO DEPARTMENT VALUES (108, 'Angular');
COMMIT;

--INSERT INTO EMPLOYEE VALUES (10005, 'Ram', 'A', 'ramA2@gmail.com', 101);
--INSERT INTO EMPLOYEE VALUES (10006, 'Vidyuth', 'RG', 'Vidyuh@gmail.com', 101);
--INSERT INTO EMPLOYEE VALUES (10007, 'Caramel', 'Joseph', 'Caram_Joseph@gmail.com', 108);
--COMMIT;
